name: App Styles / Format
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup
        with:
          node-version: ${{ matrix.node-version }}

      - name: App Install dependencies
        working-directory: ./template/web
        run: yarn --immutable

      - name: App Stylelint
        working-directory: ./template/web
        run: npm run stylelint

      - name: App Format Check
        working-directory: ./template/web
        run: npm run format:check
